/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import javax.swing.JOptionPane;

/**
 *
 * @author amufr
 */
public class fNuevaReceta extends javax.swing.JFrame {

    /**
     * Creates new form fNuevaReceta
     */
    public fNuevaReceta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        txtReceta = new javax.swing.JTextField();
        txtTiempo = new javax.swing.JTextField();
        txtIngredientes = new javax.swing.JTextField();
        nombreApellidos = new javax.swing.JLabel();
        nombreApellidos1 = new javax.swing.JLabel();
        nombreApellidos2 = new javax.swing.JLabel();
        nombreApellidos3 = new javax.swing.JLabel();
        añadir = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        txtApadirReceta = new javax.swing.JScrollPane();
        txtElaboracion = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(250, 240, 220));

        title.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(42, 27, 22));
        title.setText("Recetas Capuccino");
        title.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\amufr\\Desktop\\proyectoFinal\\src\\main\\java\\img\\logo.png")); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(logo))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo)
                .addGap(20, 20, 20))
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtReceta.setBackground(new java.awt.Color(250, 240, 220));
        txtReceta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtReceta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecetaActionPerformed(evt);
            }
        });

        txtTiempo.setBackground(new java.awt.Color(250, 240, 220));
        txtTiempo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoActionPerformed(evt);
            }
        });

        txtIngredientes.setBackground(new java.awt.Color(250, 240, 220));
        txtIngredientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngredientesActionPerformed(evt);
            }
        });

        nombreApellidos.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        nombreApellidos.setForeground(new java.awt.Color(27, 71, 45));
        nombreApellidos.setText("Nombre de la receta");

        nombreApellidos1.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        nombreApellidos1.setForeground(new java.awt.Color(27, 71, 45));
        nombreApellidos1.setText("Tiempo de elaboración");

        nombreApellidos2.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        nombreApellidos2.setForeground(new java.awt.Color(27, 71, 45));
        nombreApellidos2.setText("Receta");

        nombreApellidos3.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        nombreApellidos3.setForeground(new java.awt.Color(27, 71, 45));
        nombreApellidos3.setText("Ingredientes");

        añadir.setBackground(new java.awt.Color(255, 255, 255));
        añadir.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        añadir.setForeground(new java.awt.Color(27, 71, 45));
        añadir.setText("Añadir");
        añadir.setBorder(null);
        añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirActionPerformed(evt);
            }
        });

        volver.setBackground(new java.awt.Color(255, 255, 255));
        volver.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        volver.setForeground(new java.awt.Color(42, 27, 22));
        volver.setText("Volver");
        volver.setBorder(null);
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        txtApadirReceta.setViewportView(txtElaboracion);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApadirReceta)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreApellidos1)
                            .addComponent(nombreApellidos3)
                            .addComponent(nombreApellidos2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(nombreApellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volver)))
                .addContainerGap())
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(añadir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreApellidos)
                    .addComponent(volver))
                .addGap(1, 1, 1)
                .addComponent(txtReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nombreApellidos1)
                .addGap(4, 4, 4)
                .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(nombreApellidos3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nombreApellidos2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApadirReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(añadir)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecetaActionPerformed

    private void txtTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoActionPerformed

    private void txtIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngredientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngredientesActionPerformed

    private void añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirActionPerformed
        String receta = txtReceta.getText();
        String tiempo = txtTiempo.getText();
        String ingredientes = txtIngredientes.getText();
        String elaboracion = txtElaboracion.getText();

        if (receta.isEmpty() || tiempo.isEmpty() || ingredientes.isEmpty() || elaboracion.isEmpty()){

            JOptionPane.showMessageDialog(this, "algunos campos estan vacios");
        }
        else{
            clases.CLogin nReceta = new clases.CLogin();
            nReceta.nuevaReceta(txtReceta, txtTiempo, txtIngredientes, txtElaboracion);  
            dispose(); }// TODO add your handling code here:
    }//GEN-LAST:event_añadirActionPerformed

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        fMenu menu = new fMenu();
        menu.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_volverMouseClicked

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fNuevaReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fNuevaReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fNuevaReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fNuevaReceta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fNuevaReceta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadir;
    private javax.swing.JPanel background;
    private javax.swing.JPanel header;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nombreApellidos;
    private javax.swing.JLabel nombreApellidos1;
    private javax.swing.JLabel nombreApellidos2;
    private javax.swing.JLabel nombreApellidos3;
    private javax.swing.JLabel title;
    private javax.swing.JScrollPane txtApadirReceta;
    private javax.swing.JTextPane txtElaboracion;
    private javax.swing.JTextField txtIngredientes;
    private javax.swing.JTextField txtReceta;
    private javax.swing.JTextField txtTiempo;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
